### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by chakitg** [cp-geeks-adgitm/Hacktoberfest#185]
### **Description:**

Dijkstra's Algorithm - Write the code for Dijkstra's Algorithm and define what you have written by adding nodes in between. 👍
Do try it and enjoy! 

### **Domain**: 
C/Cpp
Java
Javascript
Python

- [ ]  Make sure to roll out safe content for the community.

**Comment by chaudharypraveen98** [comment]
Completed Thanks
